version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
    pull-request-branch-name:
      prefix: "dependabot/pip"
      separator: "/"
    target-branch: "develop"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"
      - "compose"
    pull-request-branch-name:
      prefix: "dependabot/composer"
      separator: "/"
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
    pull-request-branch-name:
      prefix: "dependabot/github-actions"
      separator: "/"
    target-branch: "develop"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"
    pull-request-branch-name:
      prefix: "dependabot/docker"
      separator: "/"
    target-branch: "develop"