from pathlib import Path
from mask import mask
import json
import requests

from defaults import DEFAULT_EMPTY_PATH,DEFAULT_CALLER_VOLUME,DEFAULT_CALLER,DEFAULT_RANDOM_CALLER,DEFAULT_RANDOM_CALLER_EACH_LEG,DEFAULT_RANDOM_CALLER_LANGUAGE,DEFAULT_RANDOM_CALLER_GENDER,DEFAULT_CALL_CURRENT_PLAYER,DEFAULT_CALL_CURRENT_PLAYER_ALWAYS,DEFAULT_CALL_EVERY_DART,DEFAULT_CALL_EVERY_DART_SINGLE_FILES,DEFAULT_POSSIBLE_CHECKOUT_CALL,DEFAULT_POSSIBLE_CHECKOUT_CALL_SINGLE_FILES,DEFAULT_POSSIBLE_CHECKOUT_CALL_YOURSELF_ONLY,DEFAULT_AMBIENT_SOUNDS,DEFAULT_AMBIENT_SOUNDS_AFTER_CALLS,DEFAULT_DOWNLOADS,DEFAULT_DOWNLOADS_LIMIT,DEFAULT_DOWNLOADS_LANGUAGE,DEFAULT_DOWNLOADS_NAME,DEFAULT_BACKGROUND_AUDIO_VOLUME,DEFAULT_WEB_CALLER,DEFAULT_WEB_CALLER_SCOREBOARD,DEFAULT_WEB_CALLER_PORT,DEFAULT_WEB_CALLER_DISABLE_HTTPS,DEFAULT_HOST_PORT,DEFAULT_DEBUG,DEFAULT_CERT_CHECK,DEFAULT_MIXER_FREQUENCY,DEFAULT_MIXER_SIZE,DEFAULT_MIXER_CHANNELS,DEFAULT_MIXER_BUFFERSIZE,DEFAULT_DOWNLOADS_PATH,DEFAULT_CALLERS_BANNED_FILE,DEFAULT_HOST_IP
from globals import AUTODART_CLIENT_ID,AUTODART_CLIENT_SECRET
from autodarts_keycloak_client import AutodartsKeycloakClient
from utils import ppi,ppe

class caller_configuration:
    VERSION: str = '0.0.1'
    AUTODART_USER_EMAIL: str
    AUTODART_USER_PASSWORD: str        
    AUTODART_USER_BOARD_ID: str      
    AUDIO_MEDIA_PATH: str
    AUDIO_MEDIA_PATH_SHARED: str = DEFAULT_EMPTY_PATH
    BLACKLIST_PATH: str = DEFAULT_EMPTY_PATH
    CALLER_VOLUME: float = DEFAULT_CALLER_VOLUME
    CALLER: str = DEFAULT_CALLER
    RANDOM_CALLER: int = DEFAULT_RANDOM_CALLER
    RANDOM_CALLER_EACH_LEG: int = DEFAULT_RANDOM_CALLER_EACH_LEG
    RANDOM_CALLER_LANGUAGE: int = DEFAULT_RANDOM_CALLER_LANGUAGE
    RANDOM_CALLER_GENDER: int = DEFAULT_RANDOM_CALLER_GENDER
    CALL_CURRENT_PLAYER: int = DEFAULT_CALL_CURRENT_PLAYER
    CALL_CURRENT_PLAYER_ALWAYS: int = DEFAULT_CALL_CURRENT_PLAYER_ALWAYS
    CALL_EVERY_DART: int = DEFAULT_CALL_EVERY_DART
    CALL_EVERY_DART_SINGLE_FILES: int = DEFAULT_CALL_EVERY_DART_SINGLE_FILES
    POSSIBLE_CHECKOUT_CALL: int = DEFAULT_POSSIBLE_CHECKOUT_CALL
    POSSIBLE_CHECKOUT_CALL_SINGLE_FILES: int = DEFAULT_POSSIBLE_CHECKOUT_CALL_SINGLE_FILES
    POSSIBLE_CHECKOUT_CALL_YOURSELF_ONLY: int = DEFAULT_POSSIBLE_CHECKOUT_CALL_YOURSELF_ONLY
    AMBIENT_SOUNDS: float = DEFAULT_AMBIENT_SOUNDS
    AMBIENT_SOUNDS_AFTER_CALLS: int = DEFAULT_AMBIENT_SOUNDS_AFTER_CALLS
    DOWNLOADS: int = DEFAULT_DOWNLOADS
    DOWNLOADS_LIMIT: int = DEFAULT_DOWNLOADS_LIMIT
    DOWNLOADS_LANGUAGE: int = DEFAULT_DOWNLOADS_LANGUAGE
    DOWNLOADS_NAME: int = DEFAULT_DOWNLOADS_NAME
    BACKGROUND_AUDIO_VOLUME: float = DEFAULT_BACKGROUND_AUDIO_VOLUME
    WEB_CALLER: int = DEFAULT_WEB_CALLER
    WEB_CALLER_SCOREBOARD: int = DEFAULT_WEB_CALLER_SCOREBOARD
    WEB_CALLER_PORT: int = DEFAULT_WEB_CALLER_PORT
    WEB_CALLER_DISABLE_HTTPS: int = DEFAULT_WEB_CALLER_DISABLE_HTTPS
    HOST_PORT: int = DEFAULT_HOST_PORT
    DEBUG: bool = DEFAULT_DEBUG
    CERT_CHECK: int = DEFAULT_CERT_CHECK
    MIXER_FREQUENCY: int = DEFAULT_MIXER_FREQUENCY
    MIXER_SIZE: int = DEFAULT_MIXER_SIZE
    MIXER_CHANNELS: int = DEFAULT_MIXER_CHANNELS
    MIXER_BUFFERSIZE: int = DEFAULT_MIXER_BUFFERSIZE
    DOWNLOADS_PATH: str = DEFAULT_DOWNLOADS_PATH
    CALLERS_BANNED_FILE: str = DEFAULT_CALLERS_BANNED_FILE
    HOST_IP: str = DEFAULT_HOST_IP
    keyCloakClient: AutodartsKeycloakClient = None

    
    def __init__(self, 
                VERSION: str = '0.0.1',
                AUTODART_USER_EMAIL: str = None,
                AUTODART_USER_PASSWORD: str = None,        
                AUTODART_USER_BOARD_ID: str = None,      
                AUDIO_MEDIA_PATH: str = None,
                AUDIO_MEDIA_PATH_SHARED: str = DEFAULT_EMPTY_PATH,
                BLACKLIST_PATH: str = DEFAULT_EMPTY_PATH,
                CALLER_VOLUME: float = DEFAULT_CALLER_VOLUME,
                CALLER: str = DEFAULT_CALLER,
                RANDOM_CALLER: int = DEFAULT_RANDOM_CALLER,
                RANDOM_CALLER_EACH_LEG: int = DEFAULT_RANDOM_CALLER_EACH_LEG,
                RANDOM_CALLER_LANGUAGE: int = DEFAULT_RANDOM_CALLER_LANGUAGE,
                RANDOM_CALLER_GENDER: int = DEFAULT_RANDOM_CALLER_GENDER,
                CALL_CURRENT_PLAYER: int = DEFAULT_CALL_CURRENT_PLAYER,
                CALL_CURRENT_PLAYER_ALWAYS: int = DEFAULT_CALL_CURRENT_PLAYER_ALWAYS,
                CALL_EVERY_DART: int = DEFAULT_CALL_EVERY_DART,
                CALL_EVERY_DART_SINGLE_FILES: int = DEFAULT_CALL_EVERY_DART_SINGLE_FILES,
                POSSIBLE_CHECKOUT_CALL: int = DEFAULT_POSSIBLE_CHECKOUT_CALL,
                POSSIBLE_CHECKOUT_CALL_SINGLE_FILES: int = DEFAULT_POSSIBLE_CHECKOUT_CALL_SINGLE_FILES,
                POSSIBLE_CHECKOUT_CALL_YOURSELF_ONLY: int = DEFAULT_POSSIBLE_CHECKOUT_CALL_YOURSELF_ONLY,
                AMBIENT_SOUNDS: float = DEFAULT_AMBIENT_SOUNDS,
                AMBIENT_SOUNDS_AFTER_CALLS: int = DEFAULT_AMBIENT_SOUNDS_AFTER_CALLS,
                DOWNLOADS: int = DEFAULT_DOWNLOADS,
                DOWNLOADS_LIMIT: int = DEFAULT_DOWNLOADS_LIMIT,
                DOWNLOADS_LANGUAGE: int = DEFAULT_DOWNLOADS_LANGUAGE,
                DOWNLOADS_NAME: int = DEFAULT_DOWNLOADS_NAME,
                BACKGROUND_AUDIO_VOLUME: float = DEFAULT_BACKGROUND_AUDIO_VOLUME,
                WEB_CALLER: int = DEFAULT_WEB_CALLER,
                WEB_CALLER_SCOREBOARD: int = DEFAULT_WEB_CALLER_SCOREBOARD,
                WEB_CALLER_PORT: int = DEFAULT_WEB_CALLER_PORT,
                WEB_CALLER_DISABLE_HTTPS: int = DEFAULT_WEB_CALLER_DISABLE_HTTPS,
                HOST_PORT: int = DEFAULT_HOST_PORT,
                CERT_CHECK: int = DEFAULT_CERT_CHECK,
                MIXER_FREQUENCY: int = DEFAULT_MIXER_FREQUENCY,
                MIXER_SIZE: int = DEFAULT_MIXER_SIZE,
                MIXER_CHANNELS: int = DEFAULT_MIXER_CHANNELS,
                MIXER_BUFFERSIZE: int = DEFAULT_MIXER_BUFFERSIZE,
                DOWNLOADS_PATH: str = DEFAULT_DOWNLOADS_PATH,
                CALLERS_BANNED_FILE: str = DEFAULT_CALLERS_BANNED_FILE,
                HOST_IP: str = DEFAULT_HOST_IP,
                DEBUG: bool = DEFAULT_DEBUG
        ):
        
        self.VERSION = VERSION

        self.AUTODART_USER_EMAIL = AUTODART_USER_EMAIL
        self.AUTODART_USER_PASSWORD = AUTODART_USER_PASSWORD
        self.AUTODART_USER_BOARD_ID = AUTODART_USER_BOARD_ID
        self.AUDIO_MEDIA_PATH = AUDIO_MEDIA_PATH

        if AUDIO_MEDIA_PATH_SHARED != DEFAULT_EMPTY_PATH: self.AUDIO_MEDIA_PATH_SHARED = Path(AUDIO_MEDIA_PATH_SHARED)
        else: self.AUDIO_MEDIA_PATH_SHARED = DEFAULT_EMPTY_PATH

        self.CALLER_VOLUME = CALLER_VOLUME
        self.CALLER = CALLER
        self.RANDOM_CALLER = RANDOM_CALLER
        self.RANDOM_CALLER_EACH_LEG = RANDOM_CALLER_EACH_LEG
        
        if RANDOM_CALLER_LANGUAGE < 0: self.RANDOM_CALLER_LANGUAGE = DEFAULT_RANDOM_CALLER_LANGUAGE
        else: self.RANDOM_CALLER_LANGUAGE = RANDOM_CALLER_LANGUAGE

        if RANDOM_CALLER_GENDER < 0: self.RANDOM_CALLER_GENDER = DEFAULT_RANDOM_CALLER_GENDER
        else: self.RANDOM_CALLER_GENDER = RANDOM_CALLER_GENDER

        self.CALL_CURRENT_PLAYER = CALL_CURRENT_PLAYER
        self.CALL_CURRENT_PLAYER_ALWAYS = CALL_CURRENT_PLAYER_ALWAYS
        self.CALL_EVERY_DART = CALL_EVERY_DART
        self.CALL_EVERY_DART_SINGLE_FILES = CALL_EVERY_DART_SINGLE_FILES
        if POSSIBLE_CHECKOUT_CALL < 0: self.POSSIBLE_CHECKOUT_CALL = 0
        else: self.POSSIBLE_CHECKOUT_CALL = POSSIBLE_CHECKOUT_CALL

        self.POSSIBLE_CHECKOUT_CALL_SINGLE_FILES = POSSIBLE_CHECKOUT_CALL_SINGLE_FILES
        self.POSSIBLE_CHECKOUT_CALL_YOURSELF_ONLY = POSSIBLE_CHECKOUT_CALL_YOURSELF_ONLY
        self.AMBIENT_SOUNDS = AMBIENT_SOUNDS
        self.AMBIENT_SOUNDS_AFTER_CALLS = AMBIENT_SOUNDS_AFTER_CALLS
        self.DOWNLOADS = DOWNLOADS
        
        if DOWNLOADS_LANGUAGE < 0: self.DOWNLOADS_LANGUAGE = DEFAULT_DOWNLOADS_LANGUAGE
        else: self.DOWNLOADS_LANGUAGE = DOWNLOADS_LANGUAGE

        if DOWNLOADS_LIMIT < 0: self.DOWNLOADS_LIMIT = DEFAULT_DOWNLOADS_LIMIT
        else: self.DOWNLOADS_LIMIT = DOWNLOADS_LIMIT

        if BLACKLIST_PATH != DEFAULT_EMPTY_PATH: self.BLACKLIST_PATH = Path(BLACKLIST_PATH)
        else: self.BLACKLIST_PATH = DEFAULT_EMPTY_PATH

        self.DOWNLOADS_NAME = DOWNLOADS_NAME
        self.BACKGROUND_AUDIO_VOLUME = BACKGROUND_AUDIO_VOLUME
        self.WEB_CALLER = WEB_CALLER
        self.WEB_CALLER_SCOREBOARD = WEB_CALLER_SCOREBOARD
        self.WEB_CALLER_PORT = WEB_CALLER_PORT
        self.WEB_CALLER_DISABLE_HTTPS = WEB_CALLER_DISABLE_HTTPS
        self.HOST_PORT = HOST_PORT
        self.DEBUG = DEBUG
        self.CERT_CHECK = CERT_CHECK
        self.MIXER_FREQUENCY = MIXER_FREQUENCY
        self.MIXER_SIZE = MIXER_SIZE
        self.MIXER_CHANNELS = MIXER_CHANNELS
        self.MIXER_BUFFERSIZE = MIXER_BUFFERSIZE
        self.DOWNLOADS_PATH = DOWNLOADS_PATH
        self.CALLERS_BANNED_FILE = CALLERS_BANNED_FILE
        self.HOST_IP = HOST_IP

        
        if DEBUG:
            ppi('Started with following arguments:')
            data_to_mask = {
                "autodarts_email": "email", 
                "autodarts_password": "str",
                "autodarts_board_id": "str"
            }
            masked_args = mask(self, data_to_mask)
            ppi(json.dumps(masked_args, indent=4))

        self.keyCloakClient = AutodartsKeycloakClient(username=AUTODART_USER_EMAIL, 
                                    password=AUTODART_USER_PASSWORD, 
                                    client_id=AUTODART_CLIENT_ID, 
                                    client_secret=AUTODART_CLIENT_SECRET,
                                    debug=DEBUG
                                    )
        self.keyCloakClient.start()